In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # data visualization
import matplotlib.pyplot as plt # data visualization

In [2]:
df = pd.read_csv('../input/fifa-22-complete-player-dataset/players_22.csv')
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (25,108) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [3]:
def low_number(value):
    color = 'red' if value < 92 else 'black'
    return 'color: %s'%color 
df[['overall','potential']].head().style.applymap(low_number)

In [4]:
df.head(2).style.applymap(low_number, subset=['overall', 'potential'])

In [5]:
def highlight_max(column):
    is_max = column == column.max()
    return ['background-color: yellow' if x else '' for x in is_max]

df.head(5).style.apply(highlight_max, subset=['age','overall','potential'])

In [6]:
df[['overall','potential']].head(5).style.applymap(low_number).apply(highlight_max)

In [7]:
# Cria um campo condicional a outro
df['age_class'] = np.where(df['age']>30, 'old', 'young') # import numpy as np
df['age_class']

0          old
1          old
2          old
3        young
4        young
         ...
19234    young
19235    young
19236    young
19237    young
19238    young
Name: age_class, Length: 19239, dtype: object

In [8]:
df.agg({'age':['min','max','mean','median','skew'],'overall':['min','max','mean','median','skew']})

              age    overall
min     16.000000  47.000000
max     54.000000  93.000000
mean    25.210822  65.772182
median  25.000000  66.000000
skew     0.431183   0.081602

In [9]:
df.groupby('nationality_name')['age','overall'].mean().sort_values(by='overall',ascending=False)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

                                age    overall
nationality_name
Tanzania                  28.000000  74.000000
Libya                     27.000000  73.333333
Mozambique                29.500000  73.000000
Central African Republic  27.500000  72.500000
Egypt                     25.583333  72.250000
...                             ...        ...
Guyana                    22.142857  57.714286
India                     24.044843  53.717489
Hong Kong                 23.000000  53.000000
South Sudan               21.200000  52.800000
Indonesia                 19.000000  51.000000

[163 rows x 2 columns]

In [10]:
pd.pivot_table(df,index='nationality_name',aggfunc=np.mean)

,age,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,club_contract_valid_until,club_jersey_number,club_team_id,defending,...,skill_curve,skill_dribbling,skill_fk_accuracy,skill_long_passing,skill_moves,sofifa_id,value_eur,wage_eur,weak_foot,weight_kg
nationality_name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,23.000000,58.000000,64.000000,35.000000,58.000000,62.000000,2023.000000,11.000000,111091.000000,31.000000,...,51.000000,68.000000,47.000000,43.000000,2.000000,243680.000000,8.750000e+05,2000.000000,3.000000,61.000000
Albania,25.413043,50.630435,48.065217,53.065217,60.304348,43.847826,2022.956522,21.630435,34617.913043,50.627907,...,48.326087,58.086957,42.282609,52.934783,2.500000,234436.086957,2.734891e+06,10133.695652,3.021739,74.673913
Algeria,26.784314,57.098039,51.568627,54.588235,64.235294,49.176471,2023.058824,22.607843,35285.254902,51.222222,...,55.352941,62.607843,50.274510,58.372549,2.764706,229512.921569,6.217549e+06,20552.941176,3.156863,74.803922
Andorra,31.000000,53.000000,28.000000,68.000000,56.000000,41.000000,2022.000000,3.000000,1757.000000,60.000000,...,37.000000,52.000000,29.000000,57.000000,2.000000,192937.000000,4.000000e+05,1000.000000,3.000000,79.000000
Angola,24.588235,55.705882,52.235294,55.647059,63.470588,52.882353,2022.823529,27.764706,26478.235294,47.176471,...,54.882353,65.235294,45.470588,56.588235,2.823529,230111.000000,2.522059e+06,9270.588235,2.941176,71.294118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,24.816038,46.193396,45.250000,50.089623,57.405660,40.764151,2022.580189,18.283019,100568.094340,47.753927,...,42.919811,51.721698,40.636792,49.528302,2.320755,247292.933962,1.318632e+06,2861.084906,2.778302,72.353774
Vietnam,27.000000,14.000000,5.000000,11.000000,23.000000,8.000000,2022.000000,1.000000,101148.000000,NaN,...,12.000000,11.000000,12.000000,23.000000,1.000000,244807.000000,5.250000e+05,2000.000000,2.000000,88.000000
Wales,24.094891,48.357664,43.642336,50.372263,56.014599,40.605839,2022.620438,19.072993,12012.467153,51.585366,...,45.854015,53.722628,40.693431,51.357664,2.248175,226616.751825,1.710657e+06,9582.481752,2.985401,74.160584
Zambia,25.555556,53.111111,63.000000,60.555556,58.555556,58.888889,2023.111111,19.222222,36462.666667,39.888889,...,52.666667,63.777778,42.777778,48.666667,2.777778,230540.888889,4.577778e+06,19388.888889,3.000000,75.111111
Zimbabwe,25.615385,53.384615,52.846154,61.461538,60.846154,48.000000,2022.923077,20.846154,26471.923077,49.076923,...,52.153846,64.153846,44.076923,53.076923,2.538462,229179.230769,2.776154e+06,12307.692308,3.230769,73.538462

In [11]:
pd.pivot_table(df,index='nationality_name',columns='club_name',values=['attacking_crossing','attacking_finishing','attacking_heading_accuracy'],aggfunc=np.mean)

                    attacking_crossing                                  \
club_name        1. FC Heidenheim 1846 1. FC Kaiserslautern 1. FC Köln
nationality_name
Afghanistan                        NaN                  NaN        NaN
Albania                            NaN                  NaN        NaN
Algeria                            NaN                  NaN        NaN
Andorra                            NaN                  NaN        NaN
Angola                             NaN                  NaN        NaN
...                                ...                  ...        ...
Venezuela                          NaN                  NaN        NaN
Vietnam                            NaN                  NaN        NaN
Wales                              NaN                  NaN        NaN
Zambia                             NaN                  NaN        NaN
Zimbabwe                           NaN                  NaN        NaN

                                                                   \
club_name        1. FC Magdeburg 1. FC Nürnberg 1. FC Saarbrücken
nationality_name
Afghanistan                  NaN            NaN               NaN
Albania                      NaN            NaN               NaN
Algeria                      NaN            NaN               NaN
Andorra                      NaN            NaN               NaN
Angola                       NaN            NaN               NaN
...                          ...            ...               ...
Venezuela                    NaN            NaN               NaN
Vietnam                      NaN            NaN               NaN
Wales                        NaN            NaN               NaN
Zambia                       NaN            NaN               NaN
Zimbabwe                     NaN            NaN               NaN

                                                                      \
club_name        1. FC Union Berlin 1. FSV Mainz 05 12 de Octubre FC
nationality_name
Afghanistan                     NaN             NaN              NaN
Albania                         NaN             NaN              NaN
Algeria                         NaN             NaN              NaN
Andorra                         NaN             NaN              NaN
Angola                          NaN            64.0              NaN
...                             ...             ...              ...
Venezuela                       NaN             NaN              NaN
Vietnam                         NaN             NaN              NaN
Wales                           NaN             NaN              NaN
Zambia                          NaN             NaN              NaN
Zimbabwe                        NaN             NaN              NaN

                             ... attacking_heading_accuracy              \
club_name        AC Ajaccio  ...        Yokohama F. Marinos Yokohama FC
nationality_name             ...
Afghanistan             NaN  ...                        NaN         NaN
Albania                67.0  ...                        NaN         NaN
Algeria                 NaN  ...                        NaN         NaN
Andorra                 NaN  ...                        NaN         NaN
Angola                  NaN  ...                        NaN         NaN
...                     ...  ...                        ...         ...
Venezuela               NaN  ...                        NaN         NaN
Vietnam                 NaN  ...                        NaN         NaN
Wales                   NaN  ...                        NaN         NaN
Zambia                  NaN  ...                        NaN         NaN
Zimbabwe                NaN  ...                        NaN         NaN

                                                                               \
club_name        Yukatel Kayserispor Zagłębie Lubin Çaykur Rizespor Örebro SK
nationality_name
Afghanistan                      NaN            NaN             NaN       NaN
Albania                          NaN            NaN             NaN      61.0
Algeria                          NaN            NaN             NaN       NaN
Andorra                          NaN            NaN             NaN       NaN
Angola                           NaN            NaN             NaN       NaN
...                              ...            ...             ...       ...
Venezuela                        NaN            NaN             NaN       NaN
Vietnam                          NaN            NaN             NaN       NaN
Wales                            NaN            NaN             NaN       NaN
Zambia                           NaN            NaN             NaN       NaN
Zimbabwe                         NaN            NaN             NaN       NaN

                                                       \
club_name        Östersunds FK İstanbul Başakşehir FK
nationality_name
Afghanistan                NaN                    NaN
Albania                    NaN                    NaN
Algeria                    NaN                    NaN
Andorra                    NaN                    NaN
Angola                     NaN                    NaN
...                        ...                    ...
Venezuela                  NaN                    NaN
Vietnam                    NaN                    NaN
Wales                      NaN                    NaN
Zambia                     NaN                    NaN
Zimbabwe                   NaN                    NaN


club_name        İttifak Holding Konyaspor Śląsk Wrocław
nationality_name
Afghanistan                            NaN           NaN
Albania                               56.5           NaN
Algeria                                NaN           NaN
Andorra                                NaN           NaN
Angola                                 NaN           NaN
...                                    ...           ...
Venezuela                              NaN           NaN
Vietnam                                NaN           NaN
Wales                                  NaN           NaN
Zambia                                 NaN           NaN
Zimbabwe                               NaN           NaN

[163 rows x 2103 columns]

In [12]:
df.nationality_name.value_counts()

England             1719
Germany             1214
Spain               1086
France               980
Argentina            960
                    ...
Ethiopia               1
Papua New Guinea       1
Kyrgyzstan             1
Guam                   1
Indonesia              1
Name: nationality_name, Length: 163, dtype: int64

In [13]:
df.nationality_name.value_counts(normalize=True)

England             0.089350
Germany             0.063101
Spain               0.056448
France              0.050938
Argentina           0.049899
                      ...
Ethiopia            0.000052
Papua New Guinea    0.000052
Kyrgyzstan          0.000052
Guam                0.000052
Indonesia           0.000052
Name: nationality_name, Length: 163, dtype: float64

In [14]:
df.groupby('club_name')['nationality_name'].value_counts()

club_name              nationality_name
1. FC Heidenheim 1846  Germany                   23
                       Austria                    2
                       Bosnia and Herzegovina     1
                       Italy                      1
1. FC Kaiserslautern   Germany                   25
                                                 ..
Śląsk Wrocław          Slovakia                   2
                       Croatia                    1
                       Czech Republic             1
                       Hungary                    1
                       Portugal                   1
Name: nationality_name, Length: 5565, dtype: int64

## SQL no Pandas

In [15]:
import pandasql as ps

In [16]:
query = """
    SELECT short_name, age, overall 
    FROM df
    ORDER BY overall DESC
    LIMIT 10
"""

In [17]:
ps.sqldf(query,locals())

          short_name  age  overall
0           L. Messi   34       93
1     R. Lewandowski   32       92
2  Cristiano Ronaldo   36       91
3          Neymar Jr   29       91
4       K. De Bruyne   30       91
5           J. Oblak   28       91
6          K. Mbappé   22       91
7           M. Neuer   35       90
8      M. ter Stegen   29       90
9            H. Kane   27       90

In [18]:
df.isnull().sum().sort_values(ascending=False)

nation_jersey_number    18480
nation_logo_url         18480
nation_position         18480
nation_team_id          18480
club_loaned_from        18137
                        ...
skill_fk_accuracy           0
skill_curve                 0
skill_dribbling             0
attacking_volleys           0
age_class                   0
Length: 111, dtype: int64

In [19]:
df.head().fillna('0')

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,age_class
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,old
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png,old
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,old
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,0,https://cdn.sofifa.net/flags/br.png,young
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png,young

In [20]:
numeric_columns = df.select_dtypes(include=['float16','float32','float64','int16','int32','int64'])
categoric_columns = df.select_dtypes(exclude=['float16','float32','float64','int16','int32','int64'])

In [21]:
for i in df.columns.sort_values():
    print(i)

age
age_class
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
body_type
cam
cb
cdm
cf
club_contract_valid_until
club_flag_url
club_jersey_number
club_joined
club_loaned_from
club_logo_url
club_name
club_position
club_team_id
cm
defending
defending_marking_awareness
defending_sliding_tackle
defending_standing_tackle
dob
dribbling
gk
goalkeeping_diving
goalkeeping_handling
goalkeeping_kicking
goalkeeping_positioning
goalkeeping_reflexes
goalkeeping_speed
height_cm
international_reputation
lam
lb
lcb
lcm
ldm
league_level
league_name
lf
lm
long_name
ls
lw
lwb
mentality_aggression
mentality_composure
mentality_interceptions
mentality_penalties
mentality_positioning
mentality_vision
movement_acceleration
movement_agility
movement_balance
movement_reactions
movement_sprint_speed
nation_flag_url
nation_jersey_number
nation_logo_url
nation_position
nation_team_id
nationality_id
nationality_name
overall
pace
passing
physic
player_face_url
player_positions
player_tags
player_traits
player_url
potential
power_jumping
power_long_shots
power_shot_power
power_stamina
power_strength
preferred_foot
ram
rb
rcb
rcm
rdm
real_face
release_clause_eur
rf
rm
rs
rw
rwb
shooting
short_name
skill_ball_control
skill_curve
skill_dribbling
skill_fk_accuracy
skill_long_passing
skill_moves
sofifa_id
st
value_eur
wage_eur
weak_foot
weight_kg
work_rate

In [22]:
def dobrar_salario(value):
    x = value*2
    return x

df['wage_eur_dobrado'] = df['wage_eur'].apply(dobrar_salario)
df[['wage_eur_dobrado','wage_eur']].head()

   wage_eur_dobrado  wage_eur
0          640000.0  320000.0
1          540000.0  270000.0
2          540000.0  270000.0
3          540000.0  270000.0
4          700000.0  350000.0

In [23]:
df['age_class2'] = 'young'
df.loc[df['age'] > 30, 'age_class2'] = 'old'
df.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url,age_class,wage_eur_dobrado,age_class2
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png,old,640000.0,old
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png,old,540000.0,old
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png,old,540000.0,old
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png,young,540000.0,young
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png,young,700000.0,young

In [24]:
pd.util.testing.makeDataFrame()

/opt/conda/lib/python3.7/site-packages/pandas/util/__init__.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing

                   A         B         C         D
fz1ChBOkUy -1.586024 -0.071227 -0.954749 -0.321484
L3P6pw4fuQ -1.294163 -1.115809 -2.239102  0.340291
D3379JDSI7  0.627947 -0.495509 -0.181775  0.305362
QCdspfOsUS -0.839679  0.538675 -1.195274 -0.940209
3uqX00e6j8 -0.096065 -1.725906 -0.803807  0.473242
sboJaeYzTH  1.057065  1.228429 -1.088865 -0.577145
Xdq9rtYpvI  0.672575  0.564358 -0.161899 -1.672467
NQf3JGIh8j  0.233071  0.070835 -0.578840 -0.636113
BDfvaKuxlq -0.422290  1.058861 -0.020548  0.852633
tlAmDkiJRf  0.963121  0.604763 -0.376360  0.124093
N8slLMEsJT  0.131187 -0.624745  0.813071 -0.615781
4rEo8YTfE6 -0.208767  0.101469  0.873489 -1.920353
7xeOfgpb0a  0.232315 -1.295630 -0.362786 -2.064015
glxbomo80v -0.624954 -0.716350 -2.360906 -0.802603
6IHplHy31K -0.805953 -1.661046  0.546925  0.078029
6im2BF5H4E  1.883505  0.366467 -0.211792 -0.073405
0ddpDNe9QL -1.008902  0.523482 -0.035752  0.731653
DuDiVmkbsp -0.541298  0.997916  1.122602  0.222026
AYmj2AIQde  0.611212  0.553943  0.173002  0.311728
c3OWdtDkhw  0.765295  0.740011  1.745768  0.210891
VQi8NR8C5L -1.302099 -0.626309  0.475153  1.893014
g9T4n7YFut -0.648112  0.539707 -0.807270 -0.859249
27le0q1U4d  0.925743  0.427509 -0.246982  0.272006
PYrAzHtBH0  0.034033  0.670201 -1.193863  0.256019
EQ3eivL8vW  0.043136  0.807372  0.375413 -0.796426
gphljRskl9  0.323016 -1.564280 -1.106184 -2.291658
TaF3kY52ZU -1.456552 -1.034068 -1.472207 -0.599122
7nHWDwYfFK -0.563050 -1.669876 -1.255598 -0.127236
HLy5Xbp3t5  0.573004 -2.138960 -0.211902  1.450974
FF0KHpF2UF -0.879344  0.985268 -0.618382 -0.924312